# Netlify Build Settings for PRODUCTION builds
[build]
  command = "npm run build"
  publish = "build/client"

# NEW: Settings for Preview/Development servers
[dev]
  command = "npm run dev"

# SPA Redirect Rule (still needed for production)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200